#!/usr/bin/env ruby
#
# Script to create a valid candlepin export.zip which can then be imported
# for an owner. Creates everything necessary, starting with a fresh owner,
# admin user, candlepin consumer, products, subs, pools, and entitlements.
#
# None of the above will be cleaned up.

require  "../../client/ruby/candlepin_api"
require 'pp'

require 'benchmark'

ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
HOST = "localhost"
PORT = 8443

def random_string prefix=nil
  prefix ||= "rand"
  return "#{prefix}-#{rand(100000)}"
end

cp = Candlepin.new(ADMIN_USERNAME, ADMIN_PASSWORD, nil, nil, HOST, PORT)

owner = cp.create_owner random_string("consumertest")
puts "Created owner: #{owner['key']}"

prod_attrs = {}
(0..20).each do |i|
  prod_attrs[random_string("attr")] = random_string("val")
end
prod_attrs['multi-entitlement'] = "yes"
product1 = cp.create_product(random_string(), random_string(),
  {:attributes => prod_attrs})

ent_count = 100

all_provided_products = [random_string(), random_string(), random_string(), random_string(), random_string(), random_string()]
all_provided_products.each do |pid|
  cp.create_product(pid, pid, {})
end

Benchmark.bm (10) do |x|
  x.report("Creating #{ent_count} pools:") {
    end_date = Date.new(2025, 5, 29)
    (0..ent_count).each do |i|
      sub1 = cp.create_subscription(owner['key'], product1['id'], 1, all_provided_products.sample(4), '', '12345', nil, nil, end_date)
    end
  }
end

Benchmark.bm (10) do |x|
  x.report("Refresh:") {
    cp.refresh_pools(owner['key'])
  }
end

org_admin_username = random_string("orgadmin")
org_admin_password = 'password'
cp.create_user(org_admin_username, org_admin_password, true)
org_admin_cp = Candlepin.new(org_admin_username, org_admin_password)
facts = {
    "distributor_version" => "sat-6.0",
    "satellite_version" => "6.0",
    "system.certificate_version" => "3.0"
}
consumer = org_admin_cp.register(random_string('dummyconsumer'), "candlepin",
  nil, facts, nil, owner['key'])
puts "Created consumer: id = #{consumer['id']}, uuid = #{consumer['uuid']}"
consumer_cp = Candlepin.new(nil, nil, consumer['idCert']['cert'], consumer['idCert']['key'],
  HOST, PORT)

pools = cp.list_owner_pools(owner['key'])
puts "Grabbing #{ent_count} entitlements"

Benchmark.bm (10) do |x|
  i = 1
  pools.each do |pool|
    x.report("Binding #{i}:") {
      consumer_cp.consume_pool(pool['id'])
    }
    i = i + 1
  end
end

Benchmark.bm (10) do |x|
  x.report("GET:") {
    consumer_cp.get_consumer(consumer['uuid'])
  }
end

#pp consumer_cp.list_entitlements()
